root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go test -v ./..."
  bin = ""
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = "0s"

[log]
  main_only = false
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false